### ISSUE TITLE
Error uploading screenshots

### ISSUE THREAD

**Issue by gilbert-jolly** [onesky/auto-screenshot-android#16]
After pressing the screenshot button, the following exception is printed:

    04-27 11:55:17.035 24318-24318/com.angazadesign.agent E/OneSkyScreenshotHelper: error uploading screenshots to server
                                                                                org.apache.http.client.HttpResponseException: Not Found
                                                                                    at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:71)
                                                                                    at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:59)
                                                                                    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:688)
                                                                                    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:658)
                                                                                    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:647)
                                                                                    at com.oneskyapp.screenshot.OneSkyScreenshotHelper$UploadAsyncTask.doInBackground(OneSkyScreenshotHelper.java:520)
                                                                                    at com.oneskyapp.screenshot.OneSkyScreenshotHelper$UploadAsyncTask.doInBackground(OneSkyScreenshotHelper.java:447)
                                                                                    at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                    at java.lang.Thread.run(Thread.java:831)

**Comment by bretdabaker** [comment]
Hi, 

What versions of Android Studio and Android OS are you testing with?

**Comment by bretdabaker** [comment]
Please also make sure the project id you provide is correct. 
`org.apache.http.client.HttpResponseException: Not Found` happens when the project can not be found.

**Comment by gilbert-jolly** [comment]
Using the correct project id fixed it, thanks
