### ISSUE TITLE
Auto upload screenshot not working

### ISSUE THREAD

**Issue by iordachiv** [onesky/auto-screenshot-android#17]
On android screenshot button click get this error:
E/OneSkyScreenshotHelper: error uploading screenshots to server
                                                                                    org.apache.http.client.HttpResponseException: Bad Request
                                                                                        at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:76)
                                                                                        at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:72)
                                                                                        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:662)
                                                                                        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:632)
                                                                                        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:621)
                                                                                        at com.oneskyapp.screenshot.OneSkyScreenshotHelper$UploadAsyncTask.doInBackground(OneSkyScreenshotHelper.java:565)
                                                                                        at com.oneskyapp.screenshot.OneSkyScreenshotHelper$UploadAsyncTask.doInBackground(OneSkyScreenshotHelper.java:492)
                                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                        at java.lang.Thread.run(Thread.java:818)
Credentials and project id is double checked.
Tested on Nexus 9 (android 6.0.1)

**Comment by bretdabaker** [comment]
We have tested with your API key and secret and was able to upload a screenshot, please make sure your API key and secret do not contain a space character at the end.

It might happen if you copy the API key / secret by highlighting with your mouse instead of double clicking.

**Comment by iordachiv** [comment]
No, this is not a solution, all credentials are right.

**Comment by bretdabaker** [comment]
Can you share the part of code where you set up the library with me at bret@oneskyapp.com?

We were not able to reproduce the issue with your credentials so it's very likely a configuration problem.

Thanks!

**Comment by rocboronat** [comment]
It doesn't work for me neither. Same issue:

```java
2018-11-15 23:03:22.921 8440-8440/com.EAGINsoftware.dejaloYa.debug E/OneSkyScreenshotHelper: error uploading screenshots to server
    org.apache.http.client.HttpResponseException: Bad Request
        at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:76)
        at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:72)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:694)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:664)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:653)
        at com.oneskyapp.screenshot.OneSkyScreenshotHelper$UploadAsyncTask.doInBackground(OneSkyScreenshotHelper.java:565)
        at com.oneskyapp.screenshot.OneSkyScreenshotHelper$UploadAsyncTask.doInBackground(OneSkyScreenshotHelper.java:492)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

Checked the credentials and also good.

**Comment by rocboronat** [comment]
Anyone there?

**Comment by rubyluk** [comment]
@rocboronat Could you attach the param to support@oneskyapp.com? Sorry for the inconvenience.

**Comment by HossamYoussof** [comment]
I have same issue

**Comment by Mknsri** [comment]
I also have this problem with the lates version of this library.
I dug around for the body and this is the response of the request:
`{"meta":{"status":400,"message":"The following JSON error has happened: No error"},"data":{}}`

**Comment by BubiDevs** [comment]
Same issue on the iOS library 😓
