### ISSUE TITLE
ScreenshotButtonService crash when targetSdkVersion >= 26

### ISSUE THREAD

**Issue by starkej2** [onesky/auto-screenshot-android#21]
The `ScreenshotButtonService` crashes whenever targeting Android 8.0. If I set the `targetSdkVersion` to 25 and leave everything else as-is, the screenshot tool works correctly (other than the disappearing button issue mentioned in #20).

```
09-07 15:55:04.343 com.oneskyapp.screenshot.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.oneskyapp.screenshot.demo, PID: 19099
    java.lang.RuntimeException: Unable to create service com.oneskyapp.screenshot.ScreenshotButtonService: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3414)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:765)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:92)
        at com.oneskyapp.screenshot.ScreenshotButtonService.onCreate(ScreenshotButtonService.java:65)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3404)
        at android.app.ActivityThread.-wrap4(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by starkej2** [comment]
To see the crash, you can use the #22 branch and just change the `targetSdkVersion` to 26.

**Comment by jpelgrim** [comment]
Is anybody working on this? How can we help?

**Comment by jpelgrim** [comment]
Still no update on this 😞
