### ISSUE TITLE
Clicking camera icon causes a crash.

### ISSUE THREAD

**Issue by scana** [onesky/auto-screenshot-android#3]
Hi.
I'm using newest version of the library and even though I've inserted it correctly into my project, when I click the camera icon all I get is this:
`    java.lang.NullPointerException
            at com.oneskyapp.screenshot.OneSkyScreenshotHelper.captureLocalizableStrings(OneSkyScreenshotHelper.java:269)
            at com.oneskyapp.screenshot.OneSkyScreenshotHelper.captureLocalizableStrings(OneSkyScreenshotHelper.java:284)
            at com.oneskyapp.screenshot.OneSkyScreenshotHelper.captureLocalizableStrings(OneSkyScreenshotHelper.java:284)
            at com.oneskyapp.screenshot.OneSkyScreenshotHelper.captureLocalizableStrings(OneSkyScreenshotHelper.java:284)
            at com.oneskyapp.screenshot.OneSkyScreenshotHelper.captureLocalizableStrings(OneSkyScreenshotHelper.java:284)
            at com.oneskyapp.screenshot.OneSkyScreenshotHelper.captureLocalizableStrings(OneSkyScreenshotHelper.java:284)
            at com.oneskyapp.screenshot.OneSkyScreenshotHelper.captureLocalizableStrings(OneSkyScreenshotHelper.java:284)
            at com.oneskyapp.screenshot.OneSkyScreenshotHelper.captureLocalizableStrings(OneSkyScreenshotHelper.java:284)
            at com.oneskyapp.screenshot.OneSkyScreenshotHelper.captureLocalizableStrings(OneSkyScreenshotHelper.java:284)
            at com.oneskyapp.screenshot.OneSkyScreenshotHelper.captureLocalizableStrings(OneSkyScreenshotHelper.java:284)
            at com.oneskyapp.screenshot.OneSkyScreenshotHelper.captureLocalizableStrings(OneSkyScreenshotHelper.java:284)
            at com.oneskyapp.screenshot.OneSkyScreenshotHelper.getScreenshot(OneSkyScreenshotHelper.java:212)
            at com.oneskyapp.screenshot.OneSkyScreenshotHelper.capture(OneSkyScreenshotHelper.java:183)
            at com.oneskyapp.screenshot.OneSkyScreenshotHelper$ActivityMonitor$1.onClick(OneSkyScreenshotHelper.java:420)
            at android.view.View.performClick(View.java:4438)
            at android.view.View$PerformClick.run(View.java:18422)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
`

EDIT: (damn, sorry for the formatting...)

**Comment by bretdabaker** [comment]
Bug fixed in v0.6.3, commit 6fb1907

**Comment by scana** [comment]
Thanks man, It's working now :+1:
